language: python
python:
  - "2.7"

sudo: required

dist: trusty
os:
  - linux

addons:
  apt:
    packages:
        - gfortran
        - build-essential
        - libblas-dev
        - liblapack-dev
        - openmpi-bin
        - openmpi-doc
        - libopenmpi-dev

# command to install dependencies
install:
  - pip install --user -r requirements.txt
  - python setup.py install --user

# command to run tests
script: ./floatpy/tests/runtests.sh
