language: python
python:
  - "2.7"

sudo: required

dist: trusty
os:
  - linux

addons:
  apt:
    packages:
        - gfortran
        - build-essential
        - libblas-dev
        - liblapack-dev

before_install:
  - sh ./travis/install-openMPI.sh

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install

# command to run tests
script: ./floatpy/tests/runtests.sh
